diff --git a/Makefile b/Makefile
index eec60da..fd17c68 100644
--- a/Makefile
+++ b/Makefile
@@ -10,13 +10,13 @@ export TERRAFORM_VERSION ?= 1.5.7
 # licensed under BSL, which is not permitted.
 TERRAFORM_VERSION_VALID := $(shell [ "$(TERRAFORM_VERSION)" = "`printf "$(TERRAFORM_VERSION)\n1.6" | sort -V | head -n1`" ] && echo 1 || echo 0)
 
-export TERRAFORM_PROVIDER_SOURCE ?= hashicorp/null
-export TERRAFORM_PROVIDER_REPO ?= https://github.com/hashicorp/terraform-provider-null
-export TERRAFORM_PROVIDER_VERSION ?= 3.2.4
-export TERRAFORM_PROVIDER_DOWNLOAD_NAME ?= terraform-provider-null
+export TERRAFORM_PROVIDER_SOURCE ?= @TERRAFORM_PROVIDER_SOURCE@
+export TERRAFORM_PROVIDER_REPO ?= @TERRAFORM_PROVIDER_REPO@
+export TERRAFORM_PROVIDER_VERSION ?= @TERRAFORM_PROVIDER_VERSION@
+export TERRAFORM_PROVIDER_DOWNLOAD_NAME ?= @TERRAFORM_PROVIDER_DOWNLOAD_NAME@
 export TERRAFORM_PROVIDER_DOWNLOAD_URL_PREFIX ?= https://releases.hashicorp.com/$(TERRAFORM_PROVIDER_DOWNLOAD_NAME)/$(TERRAFORM_PROVIDER_VERSION)
-export TERRAFORM_NATIVE_PROVIDER_BINARY ?= terraform-provider-null_v3.2.4_x5
-export TERRAFORM_DOCS_PATH ?= docs/resources
+export TERRAFORM_NATIVE_PROVIDER_BINARY ?= @TERRAFORM_NATIVE_PROVIDER_BINARY@
+export TERRAFORM_DOCS_PATH ?= @TERRAFORM_DOCS_PATH@
 
 
 PLATFORMS ?= linux_amd64 linux_arm64
