name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: nix-runners
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            allowUnfree = true

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check

      - run: >
          nix build
          .#chart-releaser
          .#kubectl-get-all
          .#kubectl-get-resources
          .#mmake
          .#openshift-installer
