name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: nix-runners
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            allowUnfree = true

      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check

      - run: >
          nix build
          .#chart-releaser
          .#kubectl-get-all
          .#kubectl-get-resources
          .#mmake
          .#openshift-installer
